name: Test Automation Workflow
on:
  schedule:
    - cron: 00 18 * * *
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation Framework with Maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=false -DisHeadLess=false
    
    - name: Upload  Test logs
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
       name: Test logs
       path: logs/

    - name: Upload Screenshots as Artifacts
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: screenshots
        path: screenshots/

    - name: Upload HTML Report as Artifact
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: html-report
        path: report.html
       
    - name: Test Execution Status
      if: always()
      run: echo "Test Execution Completed"
